
_EVT_INIT = 'INITIALIZE'
EVT_START = 'START'
EVT_READY = 'READY'
EVT_CLOSE  = 'CLOSE'
EVT_APP_LOAD = 'APP_LOAD'
EVT_APP_UNLOAD = 'APP_UNLOAD'
EVT_INTENT_SUBSCRIBE = 'INTENT_SUBSCRIBE'
EVT_INTENT_START = 'INTENT_START'
EVT_INTENT_END = 'INTENT_END'

EVT_ANY = '*'

_META_EVENTS = (
    _EVT_INIT, EVT_APP_LOAD, EVT_APP_UNLOAD,
    EVT_INTENT_SUBSCRIBE, EVT_INTENT_START, EVT_INTENT_END
)
